// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1Jituhv9wv8C36s6EAZh0jCNr3Cd6U8',
    appId: '1:314577921533:web:f2517f02f9b46d4b956594',
    messagingSenderId: '314577921533',
    projectId: 'babuland-8e3ec',
    authDomain: 'babuland-8e3ec.firebaseapp.com',
    databaseURL: 'https://babuland-8e3ec.firebaseio.com',
    storageBucket: 'babuland-8e3ec.appspot.com',
    measurementId: 'G-V8J5FS9EQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92utVQDlVrBx-WTto4l-cVIYIDSROHjY',
    appId: '1:314577921533:android:2f118a4bfa12f434956594',
    messagingSenderId: '314577921533',
    projectId: 'babuland-8e3ec',
    databaseURL: 'https://babuland-8e3ec.firebaseio.com',
    storageBucket: 'babuland-8e3ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGodcngN-m62H7yNQ8QLDVDvZ1-c51VI0',
    appId: '1:314577921533:ios:ffc0a47ad517f99a956594',
    messagingSenderId: '314577921533',
    projectId: 'babuland-8e3ec',
    databaseURL: 'https://babuland-8e3ec.firebaseio.com',
    storageBucket: 'babuland-8e3ec.appspot.com',
    androidClientId: '314577921533-32evov6k2dh5bujnletr8l28rpjf190j.apps.googleusercontent.com',
    iosClientId: '314577921533-lcolb04m3mljc62hgqv7evaepl70imrc.apps.googleusercontent.com',
    iosBundleId: 'com.babuland.babuland',
  );
}
